version: '3.9'
services:
  nfs-server:
    image: slayerus/ganesha:latest
    container_name: nfs-server
    #restart: always
    # environment:
    #   - EXPORT_PATH=/exports/nfs
    #   - PROTOCOLS=4
    # cap_add:
    #   - SYS_ADMIN
    #   - DAC_READ_SEARCH
    # security_opt:
    #   - apparmor=erichough-nfs
    privileged: true
    volumes:
      - /mnt/nfs-store:/exports
      - ./ganesha_debian/ganesha.conf:/etc/ganesha/ganesha.my.conf:ro
    ports:
      - "2049:2049"
      # - "111:111/udp"
      # - "111:111"
      # - "662:662"
      # - "38465:38465"
      # - "38466:38466"
      # - "38467:38467"
    networks:
      - nfs-store
networks:
  nfs-store:
    name: nfs-store
    driver: bridge

