version: '3.9'
services:
  nfs-server:
    image: erichough/nfs-server:latest
    container_name: nfs-server
    #restart: always
    environment:
      - NFS_EXPORT_0=/exports *(rw,sync,crossmnt,no_subtree_check,fsid=0,no_root_squash)
      - NFS_EXPORT_1=/exports/gitlab *(rw,sync,no_subtree_check,no_root_squash)
      - NFS_VERSION=4.2
      - NFS_DISABLE_VERSION_3=1
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor=erichough-nfs
    # privileged: true
    volumes:
      - /mnt/nfs-store:/exports
    ports:
      - 2049:2049
    networks:
      - nfs-store
networks:
  nfs-store:
    name: nfs-store
    driver: bridge

