apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-local-pv
  # namespace: nfs
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    #- ReadOnlyMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-local-storage
  hostPath:
    path: "/mnt/data_store/nfs"