kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  # namespace: nfs
  labels:
    app: nfs-server
spec:
  type: ClusterIP
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
    # - name: mountd
    #   port: 20048
    # - name: rpcbind
    #   port: 111
    # - name: test1
    #   port: 32765
    # - name: test2
    #   port: 32766
    - name: mountd
      port: 32767
    
