# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nfs-test-vol
#   # namespace: nfs
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs-test-cl
#   nfs:
#     server: nfs-server.default.svc.cluster.local
#     path: "/test"
#   # mountOptions:
#   #   - nfsvers=4.2
#   #   - port=2049
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nfs-test-claim
#   # namespace: nfs
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs-test-cl
#   resources:
#     requests:
#       storage: 100Mi
# # ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nfs-test-role-svc
#   # namespace: nfs
#   labels:
#     app: nfs-test-role
# spec:
#   type: ClusterIP
#   selector:
#     app: nfs-test-role
#   ports:
#     - name: nfs
#       port: 2049
#       targetPort: 2049
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-test2
  # namespace: nfs
spec:
  replicas: 1
  selector:
    role: nfs-test-role
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/nfs-test-role: localhost/erichough-nfs
      labels:
        role: nfs-test-role
        app: nfs-test-role
    spec:
      containers:
      - name: nfs-test-role
        image: redis:alpine
        # ports:
        #   - name: nfs
        #     containerPort: 2049
        # securityContext:
        #   # privileged: true
        #   capabilities:
        #     add: 
        #       - SYS_ADMIN
      #   volumeMounts:
      #     - mountPath: /mnt
      #       name: nfs-mount
      # volumes:
      #   - name: nfs-mount
      #     persistentVolumeClaim:
      #       claimName: nfs-test-claim

