apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
  # namespace: nfs
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      annotations:
          container.apparmor.security.beta.kubernetes.io/nfs-server: localhost/erichough-nfs
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
          # capabilities:
          #   add: 
          #     # - SYS_ADMIN
          #     - SYS_MODULE
        volumeMounts:
          - mountPath: /exports
            name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: nfs-pv-provisioning
