apiVersion: v1
kind: ConfigMap
metadata:
  name: ganesha-conf
  labels:
    app: nfs-server
data:
  ganesha.my.conf: |+
    EXPORT_DEFAULTS
    {
        Transports = TCP,UDP;
        SecType = sys;
    }
    EXPORT
    {
        Export_Id = 1;
        Path = /exports;
        Pseudo = /;
        Protocols = 4;
        Access_Type = RW;
        Squash = no_root_squash;
        Disable_ACL = true;
        FSAL {
            Name = VFS;
        }
    }
    NFS_CORE_PARAM
    {
        NFS_Protocols = 4;
        fsid_device = true;
    }
    NFS_KRB5
    {
            Active_krb5 = false;
    }
    LOG {
        Components {
            FSAL = FULL_DEBUG;
            NFS4 = EVENT;
        }
    }
    