---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  type: ClusterIP  # use "LoadBalancer" to get a public ip
  selector:
    app: nfs-server
  ports:
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      name: nfs-server
      # annotations:
      #   container.apparmor.security.beta.kubernetes.io/nfs-server: localhost/nfs-mount-container
      labels:
        app: nfs-server
        role: nfs-server
    spec:
      # nodeSelector:
      #   "kubernetes.io/os": linux
      containers:
        - name: nfs-server
          # image: erichough/nfs-server:latest
          image: slayerus/nfs-std:alpine
          imagePullPolicy: Always
          env:
            - name: NFS_EXPORT_0
              value: "/exports *(rw,sync,crossmnt,no_subtree_check,fsid=0)"
            - name: NFS_EXPORT_1
              value: "/exports/gitlab *(rw,sync,no_subtree_check,no_root_squash)"
            - name: NFS_LOG_LEVEL
              value: DEBUG
            # - name: NFS_PORT
            #   value: '2049'
            - name: NFS_VERSION
              value: "4.2"
            - name: NFS_DISABLE_VERSION_3
              value: "1"
          volumeMounts:
            - mountPath: /exports
              name: nfs-vol
            # - mountPath: /lib/modules
            #   name: modules
            #   readOnly: true
          securityContext:
            privileged: true
            # capabilities:
              # add: 
              #   - SYS_ADMIN
              #   - SETPCAP
            #     - SYS_MODULE
          ports:
            - name: tcp-2049
              containerPort: 2049
              protocol: TCP
            - name: udp-111
              containerPort: 111
              protocol: UDP
      volumes:
        - name: nfs-vol
          hostPath:
            path: /mnt/nfs-store  # modify this to specify another path to store nfs share data
            type: DirectoryOrCreate
        # - name: modules
        #   hostPath:
        #     path: /lib/modules
