kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  # namespace: nfs
  labels:
    app: nfs-server
spec:
  type: ClusterIP
  selector:
    app: nfs-server
  ports:
    - name: nfs-tcp
      port: 2049
      targetPort: 2049
      protocol: TCP
    - name: nfs-udp
      port: 2049
      targetPort: 2049
      protocol: UDP
    # - name: mountd
    #   port: 20048
    # - name: rpcbind-tcp
    #   port: 111
    #   targetPort: 111
    #   protocol: TCP
    # - name: rpcbind-upd
    #   port: 111
    #   targetPort: 111
    #   protocol: UDP
    # - name: test1
    #   port: 32765
    # - name: test2
    #   port: 32766
    - name: mountd2
      port: 32767
